"""Small helpers for safe regeneration of legacy ingestion output."""

from __future__ import annotations

import csv
import json
import os
import shutil
import tempfile
from pathlib import Path

MANIFEST_NAME = '.generated_artifacts.json'


def _legacy_paths(target, group):
    """Return conservative paths known to be generated by an old stage."""
    paths = []
    if group == 'ingest':
        paths.extend(target / name for name in ('manifest.json', 'samples.csv'))
        data = target / 'data'
        if data.is_dir() and not data.is_symlink():
            for run in data.iterdir():
                if run.is_dir() and not run.is_symlink():
                    paths.extend(run / name for name in
                                 ('tic.csv', 'avg_spectrum.csv', 'avg_spectrum_unit.csv'))
        mzml = target / 'mzml'
        if mzml.is_dir() and not mzml.is_symlink():
            paths.extend(item for item in mzml.glob('*.mzML') if item.is_file())
        method = target / 'method'
        if method.is_dir() and not method.is_symlink():
            paths.extend(item for item in method.glob('*.acqmeth.txt') if item.is_file())
    elif group == 'plot':
        plots = target
        paths.extend(item for item in plots.glob('*.png') if item.is_file())
        for sub in ('tic', 'avg_spectrum', 'avg_spectrum_unit'):
            directory = plots / sub
            if directory.is_dir() and not directory.is_symlink():
                paths.extend(item for item in directory.glob('*.png') if item.is_file())
    elif group == 'eic':
        peaks = target / 'peaks.csv'
        if peaks.is_file():
            paths.append(peaks)
            try:
                with peaks.open(newline='', encoding='utf-8') as handle:
                    runs = {row.get('run') for row in csv.DictReader(handle)
                            if row.get('run')}
            except (OSError, csv.Error):
                runs = set()
            paths.extend(target / ('%s.csv' % run) for run in runs
                         if Path(run).name == run and run not in ('.', '..'))
        plots = target / 'plots'
        if plots.is_dir() and not plots.is_symlink():
            paths.extend(item for item in plots.glob('*.png') if item.is_file())
    return paths


def _read_manifest(target):
    path = target / MANIFEST_NAME
    if not path.is_file():
        return {'groups': {}}
    try:
        value = json.loads(path.read_text(encoding='utf-8'))
    except (OSError, ValueError):
        return {'groups': {}}
    return value if isinstance(value, dict) and isinstance(value.get('groups'), dict) \
        else {'groups': {}}


def _remove_tracked(paths):
    for path in sorted({Path(path) for path in paths}, key=lambda item: len(item.parts), reverse=True):
        if path.is_file() or path.is_symlink():
            path.unlink()


def _remove_empty_parents(paths, root):
    """Remove empty parents of removed artifacts, never unrelated directories."""
    root = Path(root)
    directories = set()
    for path in paths:
        directory = Path(path).parent
        while directory != root and root in directory.parents:
            directories.add(directory)
            directory = directory.parent
    for directory in sorted(directories, key=lambda item: len(item.parts), reverse=True):
        if directory.is_dir():
            try:
                directory.rmdir()
            except OSError:
                pass


def _manifest_paths(target, relatives):
    """Resolve only safe relative paths stored in the generated-file manifest."""
    paths = []
    resolved_target = target.resolve()
    for relative in relatives:
        path = Path(relative)
        if path.is_absolute() or '..' in path.parts:
            continue
        candidate = target / path
        try:
            parent = candidate.parent.resolve()
        except OSError:
            continue
        if parent != resolved_target and resolved_target not in parent.parents:
            continue
        paths.append(candidate)
    return paths


def unique_dataset_basenames(datasets):
    """Reject colliding ``.d`` basenames before a stage reads or writes data."""
    seen = {}
    for dataset in datasets:
        path = Path(dataset)
        name = path.name[:-2] if path.name.lower().endswith('.d') else path.name
        key = name.casefold()
        seen.setdefault(key, []).append(str(path))
    duplicates = {key: paths for key, paths in seen.items() if len(paths) > 1}
    if duplicates:
        detail = '; '.join('%s: %s' % (key, ', '.join(paths))
                           for key, paths in sorted(duplicates.items()))
        raise ValueError('duplicate_dataset_basename: %s' % detail)


def begin_output(out):
    """Return a temporary sibling directory for an all-or-nothing stage."""
    target = Path(out).expanduser()
    target.parent.mkdir(parents=True, exist_ok=True)
    return Path(tempfile.mkdtemp(prefix='.%s-stage-' % target.name,
                                 dir=str(target.parent)))


def commit_output(stage, out, *, group):
    """Replace one generated group, preserving all untracked user files."""
    stage = Path(stage)
    target = Path(out).expanduser()
    target.mkdir(parents=True, exist_ok=True)
    manifest = _read_manifest(target)
    groups = manifest.setdefault('groups', {})
    if group in groups:
        previous = _manifest_paths(target, groups[group])
    else:
        previous = _legacy_paths(target, group)
    _remove_tracked(previous)
    _remove_empty_parents(previous, target)
    generated = [path.relative_to(stage) for path in stage.rglob('*') if path.is_file()]
    for source in sorted(stage.rglob('*')):
        if not source.is_file():
            continue
        relative = source.relative_to(stage)
        destination = target / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        os.replace(str(source), str(destination))
    groups[group] = sorted(str(path) for path in generated)
    (target / MANIFEST_NAME).write_text(
        json.dumps({'groups': groups}, indent=2) + '\n', encoding='utf-8')
    shutil.rmtree(stage, ignore_errors=True)


def discard_output(stage):
    shutil.rmtree(Path(stage), ignore_errors=True)
